ALTER TABLE EMPLOYEE DROP CONSTRAINT FK_EMPLOYEE_DEPARTMENT_ID
ALTER TABLE EMPLOYEE DROP CONSTRAINT FK_EMPLOYEE_ADDRESS_ID
ALTER TABLE EMPLOYEE DROP CONSTRAINT FK_EMPLOYEE_BOSS_ID
ALTER TABLE PHONE DROP CONSTRAINT FK_PHONE_EMPLOYEE_ID
ALTER TABLE DEPARTMENT_EMPLOYEE DROP CONSTRAINT FK_DEPARTMENT_EMPLOYEE_employees_ID
ALTER TABLE DEPARTMENT_EMPLOYEE DROP CONSTRAINT FK_DEPARTMENT_EMPLOYEE_Department_ID
ALTER TABLE PROJECT_EMPLOYEE DROP CONSTRAINT FK_PROJECT_EMPLOYEE_projects_ID
ALTER TABLE PROJECT_EMPLOYEE DROP CONSTRAINT FK_PROJECT_EMPLOYEE_employees_ID
DROP TABLE ADDRESS
DROP TABLE DEPARTMENT
DROP TABLE PROJECT
DROP TABLE EMPLOYEE
DROP TABLE PHONE
DROP TABLE DEPARTMENT_EMPLOYEE
DROP TABLE PROJECT_EMPLOYEE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
